#line_file_path: "/home/mirek/Simulace/BPC-PRP/resources/route_1.yaml"
#line_file_path: "/home/mirek/Simulace/BPC-PRP/resources/route_2.yaml"
line_file_path: "/home/mirek/Simulace/BPC-PRP/resources/route_3.yaml"

simulation:
  port: 8080
  simulation_period: 0.01
  visualization_period: 0.02
  verbose_timing: true
  verbose_udp: true

robot:
  pose:
    x: 0.0
    y: -5.0
  orientation_deg: 0.0

  wheel_radius: 0.02
  chassis_base: 0.12

  width: 0.1
  length: 0.1
  height: 0.1

  body_offset:
    x: 0.0
    y: 0.0
    z: 0.02

  line_sensors:
    - [0.00,  -0.01, 0.02]
    - [0.00,  0.01, 0.02]
    - [0.05,  -0.01, 0.02]
    - [0.05,  0.01, 0.02]
